version: 2.1

jobs:
  build-and-test:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install pytest
            pip install pytest-cov
      - run:
          name: Run tests with coverage
          command: |
            pytest --cov=my_project --cov-report=xml
      # - run:
      #     name: Upload to Codecov
      #     command: |
      #       bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test