version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4

jobs:
  build-and-test:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install pytest
            pip install pytest-cov
      - run:
          name: Run tests with coverage
          command: |
            pytest --cov=imbens --cov-report=xml
      - codecov/upload:
          file: coverage.xml

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test